int controller_cargarJugadoresDesdeTexto(char* path , LinkedList* pArrayListJugador, int *id);
int controller_cargarJugadoresDesdeBinario(char* path , LinkedList* pArrayListJugador, int *id);
int controller_agregarJugador(LinkedList* pArrayListJugador, int *idJugador);
int controller_editarJugador(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_removerJugador(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_listarJugadores(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_ordenarJugadores(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_guardarJugadoresModoTexto(char* path , LinkedList* pArrayListJugador, int id);
int controller_guardarJugadoresModoBinario(char* path , LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion, int id);
int controller_cargarSeleccionesDesdeTexto(char* path , LinkedList* pArrayListSeleccion);
void controller_listarSelecciones(LinkedList* pArrayListSeleccion);
int controller_ordenarSelecciones(LinkedList* pArrayListSeleccion);
int controller_guardarSeleccionesModoTexto(char* path , LinkedList* pArrayListSeleccion);
int controller_convocarOsacarJugador(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
